[workspace]
resolver = "2"
members = [
	"protocol",
	"master",
	"admin",
	"query",
]
default-members = ["master", "protocol"]

[profile.release]
codegen-units = 1
lto = true
# TODO: cargo 1.59
# strip = "debuginfo"
