[graph]
# Collect metadata with `--all-features`.
all-features = true

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "CC0-1.0",
    "LGPL-3.0-only",
    "MIT",
]
exceptions = [
    { allow = ["GPL-3.0-only"], crate = "xash3d-admin" },
    { allow = ["GPL-3.0-only"], crate = "xash3d-query" },
    { allow = ["Unicode-3.0"], crate = "unicode-ident" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index"
]
allow-git = []

[bans]
# Deny multiple versions of the same crate.
multiple-versions = "deny"
# Deny if a crate version requirement is `*`.
wildcards = "deny"
