[package]
name = "xash3d-protocol"
version = "0.1.0"
license = "LGPL-3.0-only"
authors = ["Denis Drakhnia <numas13@gmail.com>"]
edition = "2021"
rust-version = "1.56"

[dependencies]
thiserror = "1.0.49"
log = "<0.4.19"
bitflags = "2.4"
