
# cargo-vet audits file

[[audits.ahash]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.4.8"

[[audits.android-tzdata]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[audits.arrayvec]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.7.2 -> 0.7.4"

[[audits.bitflags]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "1.3.2"

[[audits.blake2b_simd]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.cc]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.97 -> 1.0.98"

[[audits.chrono]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.4.26"

[[audits.const-random]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.1.18"

[[audits.const-random-macro]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.1.16"

[[audits.constant_time_eq]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.1.5"

[[audits.crossterm]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.25.0"

[[audits.fastrand]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.0.1 -> 2.0.2"

[[audits.getrandom]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.2.2"

[[audits.iana-time-zone]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.59 -> 0.1.60"

[[audits.libc]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.154 -> 0.2.155"

[[audits.mio]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-run"
delta = "0.7.4 -> 0.8.11"

[[audits.numtoa]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.1.0"

[[audits.once_cell]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "1.12.0"

[[audits.redox_termios]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.1.3"

[[audits.signal-hook]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.3.17"

[[audits.signal-hook-mio]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "0.2.3"

[[audits.signal-hook-registry]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.4.1 -> 1.4.2"

[[audits.tiny-keccak]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
version = "2.0.2"

[[audits.wasm-bindgen]]
who = "Denis Drakhnia <numas13@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.91 -> 0.2.92"

[[trusted.getopts]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-08-19"
end = "2025-04-04"

[[trusted.itoa]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2025-04-04"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2025-04-04"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2025-04-04"

[[trusted.lock_api]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2025-04-07"

[[trusted.mio]]
criteria = "safe-to-deploy"
user-id = 10
start = "2019-05-15"
end = "2025-04-07"

[[trusted.num-traits]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2019-05-20"
end = "2025-04-04"

[[trusted.parking_lot]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2025-04-07"

[[trusted.parking_lot_core]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2025-04-07"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2025-04-04"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2025-04-04"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2025-04-04"

[[trusted.scopeguard]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2020-02-16"
end = "2025-04-07"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-04-04"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-04-04"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2025-04-04"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2025-04-07"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-04-04"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-04-04"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2025-04-04"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-05-16"
end = "2025-04-04"

[[trusted.wasi]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2020-06-03"
end = "2025-04-04"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2025-04-04"

[[trusted.wasm-bindgen-backend]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2025-04-04"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2025-04-04"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2025-04-04"

[[trusted.wasm-bindgen-shared]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2025-04-04"

[[trusted.windows]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-01-15"
end = "2025-04-04"

[[trusted.windows-core]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-04-04"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-04-07"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2025-04-04"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-04-04"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2025-04-04"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-04-04"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2025-06-05"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-04-04"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-04-04"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-04-04"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-04-04"

[[trusted.xash3d-admin]]
criteria = "safe-to-deploy"
user-id = 251561 # Denis Drakhnia (numas13)
start = "2024-01-28"
end = "2025-04-04"

[[trusted.xash3d-master]]
criteria = "safe-to-deploy"
user-id = 251561 # Denis Drakhnia (numas13)
start = "2024-01-28"
end = "2025-04-04"

[[trusted.xash3d-protocol]]
criteria = "safe-to-deploy"
user-id = 251561 # Denis Drakhnia (numas13)
start = "2024-01-28"
end = "2025-04-04"

[[trusted.xash3d-query]]
criteria = "safe-to-deploy"
user-id = 251561 # Denis Drakhnia (numas13)
start = "2024-01-28"
end = "2025-04-04"
