
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.xash3d-admin]
audit-as-crates-io = true

[policy.xash3d-master]
audit-as-crates-io = true

[policy.xash3d-protocol]
audit-as-crates-io = true

[policy.xash3d-query]
audit-as-crates-io = true

[[exemptions.mio]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.10"
criteria = "safe-to-deploy"
