# Default config file

#[log]
## Possible values: 0-5, off, error, warn, info, debug, trace
#level = "info"

#[server]
#ip = "0.0.0.0"
#port = 27010
## How many servers with the same ip can be registred
#max-servers-per-ip = 14

#[server.timeout]
## Time in seconds while challenge is valid
#challenge = 10
## Time in seconds while server is valid
#server = 300
## Time in seconds before next admin request is allowed after wrong password
#admin = 10

#[client]
## If client version is less then show update message
#version = "0.19"
#update_title = "https://github.com/FWGS/xash3d-fwgs"
#update_map = "Update please"
##update_addr = "mentality.rip"

#[hash]
#len = 64
#key = "Half-Life"
#personal = "Freeman"

##[[admin]]
##name = "gordon"
##password = "crowbar"

##[[admin]]
##name = "gman"
##password = "time2choose"
